name: QA-tool
run-name: QA-tool is run by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command'
        required: true
        default: 'branch-prs-report'
        type: choice
        options:
          - 'branch-prs-report'
      sourceBranch:
        description: 'Source branch'
        required: true
        default: 'dev'
      targetBranch:
        description: 'Target branch'
        required: true
        default: 'stg'
      isSimpleReport:
        description: 'Simple report without details'
        required: true
        default: false
        type: boolean

# Environment variables that are accessible for all jobs
env:
  REPO_OWNER: ${{ github.event.repository.owner.login }}
  REPO_NAME: ${{ github.event.repository.name }}

  # The path to the file where the report will be saved
  # after the completion of the QA-tool
  REPORT_FILE_PATH: pr-report.md

jobs:
  qa-tool:
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#defining-access-for-the-github_token-permissions
    permissions:
      # following two permissions are required to read the contents of the repository
      pull-requests: read
      contents: read

    steps:

      # # Debugging: uncomment the following lines to see the logs
      # - name: Logs
      #   run: |
      #     echo "event: ${{ toJson(github.event) }}"
      #     echo "Command: ${{ github.event.inputs.command }}"
      #     echo "Source branch: ${{ github.event.inputs.sourceBranch }}"
      #     echo "Target branch: ${{ github.event.inputs.targetBranch }}"
      #     echo "isSimpleReport: ${{ github.event.inputs.isSimpleReport }}"
      #     echo "Secret: ${{ toJson(secrets) }}"
      #     echo "Environment: ${{ toJson(env) }}"
      #     echo "Runner: ${{ toJson(runner) }}"
      #     ls -la
      #     pwd

      # Checkout the repository: need to access the repository
      - name: 'deps: Checkout install'
        uses: actions/checkout@v4

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run QA-tool & make a report
        env:
          # The GITHUB_TOKEN is required to access the pull requests
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          touch ${{ env.REPORT_FILE_PATH }}
          npx tsx qa-tool.ts \
            ${{ github.event.inputs.command }} \
            ${{ github.event.inputs.sourceBranch }} \
            ${{ github.event.inputs.targetBranch }} \
            --path ${{ env.REPORT_FILE_PATH }} \
            ${{ github.event.inputs.isSimpleReport == 'true' && '--simple' || '' }}

      # Upload the file as an artifact to make it downloadable
      - name: Report upload
        uses: actions/upload-artifact@v4
        with:
          name: pr-report
          # The path to the file where the report is saved
          path: ${{ runner.workspace }}/${{ env.REPO_NAME }}/${{ env.REPORT_FILE_PATH }}
